path_gams = '../../../GAMS/'
path_pycore = '../../../pycore/'
path_enz_mw = '../../../input/enz_mw_g_per_mmol.txt'
path_pro_mw = '../../../input/pro_mw_g_per_mmol.txt'
biom_id = 'BIOSYN-BIODILAERO'
biom_id_fba = 'BIOMASS'
vprod_coreid = 'EX_nrgn_e'
vprod = 'RXNADD-EX_nrgn_e_FWD-SPONT'
c_sources_list = [{'rxn': 'EX_glc__D_e', 'MW': 180.156, 'v': -13.21}]
prod_mw = 272.25
