path_gams = '../../../GAMS/'
path_pycore = '../../../pycore/'
path_enz_mw = '../../../input/enz_mw_g_per_mmol.txt'
path_pro_mw = '../../../input/pro_mw_g_per_mmol.txt'
biom_id = 'BIOSYN-BIODILAERO'
biom_id_fba = 'BIOMASS'
vprod_coreid = 'EX_odealc_e'
vprod = 'RXNADD-EX_odealc_e_FWD-SPONT'
c_sources_list = [{'rxn': 'EX_sucr_e', 'MW': 342.29648, 'v': -0.332925}]
prod_mw = 268.5
